[package]
name = "disable-ibc-chans-masp-migration"
description = "Disable compromised IBC tokens and enable replacements on new channels."
authors.workspace = true
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
namada_tx_prelude.workspace = true
rlsf.workspace = true
getrandom.workspace = true

[lib]
crate-type = ["cdylib"]
